language: ruby
rvm:
    - 2.4.0
install: gem install jekyll -v 3.4.1 && gem install s3_website
script: jekyll build
after_success: s3_website push
s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: tech304.io.s3-website-us-east-1.amazonaws.com
branches:
  only:
    - deploy
