# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tech304
email: tech304@intarwebs.com
description: > # this means to ignore newlines until "baseurl:"
  tech304 a community of tech & web professionals, mentors, students, and enthusiasts in West Virginia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech304.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://0.0.0.0:4000"
twitter_username: 304tech
github_username:  tech304

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
